$("#key-features").click(function(){
  $('html,body').animate({
    scrollTop: 1150 },'slow');
  });
$("#circle-one").click(function(){
  $(this).css("content","url(picture/black-circle)");
  $("#circle-two").css("content","url(picture/black-side)");
  $("#circle-three").css("content","url(picture/black-side)");
  $("#circle-four").css("content","url(picture/black-side)");
  $('html,body').animate({
    scrollTop: 1150},'slow');
  });
$("#circle-two").click(function(){
  $(this).css("content","url(picture/black-circle)");
  $("#circle-one").css("content","url(picture/black-side)");
  $("#circle-three").css("content","url(picture/black-side)");
  $("#circle-four").css("content","url(picture/black-side)");
  });
$("#circle-three").click(function(){
  $(this).css("content","url(picture/black-circle)");
  $("#circle-two").css("content","url(picture/black-side)");
  $("#circle-one").css("content","url(picture/black-side)");
  $("#circle-four").css("content","url(picture/black-side)");
  });
$("#circle-four").click(function(){
  $(this).css("content","url(picture/black-circle)");
  $("#circle-two").css("content","url(picture/black-side)");
  $("#circle-one").css("content","url(picture/black-side)");
  $("#circle-four").css("content","url(picture/black-side)");
  });
